---
dist: bionic
language: c
addons:
  apt:
    packages:
      - gettext
      - git
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-tools
      - libgoocanvas-2.0-dev
      - libgspell-1-dev
      - libgstreamer1.0-dev
      - libgtksourceview-3.0-dev
      - libplist-dev
      - libwebkit2gtk-4.0-dev
      - libxml2-utils
      - ninja-build
      - python3-pip
      - python3-setuptools
      - shared-mime-info
      - xvfb
env:
  - CFLAGS=-fdiagnostics-color

# Make a fake NI compiler binary so we don't have to download a closed source blob
before_script:
  - echo '#!/bin/sh' >src/ni/ni
  - echo echo Inform 7 build `head -n1 meson.build | grep -oE '[0-9][A-Z][0-9]{2}'` has started. >>src/ni/ni
  - chmod u+x src/ni/ni
  # Install a newer version of Meson
  - pip3 install meson

script:
  - meson _build
  - ninja -C _build
  - xvfb-run -a meson test -C _build

after_failure:
  - cat _build/meson-logs/*.txt
